version: '3'
services:
  front-end:
    build:
      context: ./front-end/hbsis-project
      dockerfile: ./front-end/hbsis-project/Dockerfile
    networks:
      - production-network
    hostname: front-end
    container_name: front-end
    port:
      - 3000:3000
  back-end:
    build:
      context: ./back-end
      dockerfile: ./back-end/Dockerfile
    networks:
      - production-network
    hostname: back-end
    container_name: back-end
    port: 
      - 8080
    depends_on: mongodb
  mongodb:
    image: mongo:latest
    ports: 
      - 8081
    networks: 
      - production-network
    hostname: mongo
    container_name: mongo
  networks:
    production-network:
      driver: bridge
